(feat) O3-2798: Adding metrics extension slot to the refApp
openmrs/openmrs-esm-home pull request #183
Opened 2024-02-13 12:05 UTC by arodidev

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR introduces an extension slot that will cater for the addition of metrics widgets to the home page of the Ref App

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-02-29 08:38 UTC, CynthiaKamau reviewed
Thanks @arodidev for this, perhaps instead of `test` you could use something like `common` or `template` so that people get that it is to be used as a starter. Otherwise LGTM

2024-02-29 08:39 UTC, CynthiaKamau commented on packages/esm-home-app/src/homepage-metrics/TestDataTile.component.tsx
> +import styles from './home-metrics-widget.scss';
You can seperate the styles or have a single file that will insinuate that its used by many files

2024-03-05 09:20 UTC, arodidev commented
> Thanks @arodidev for this, perhaps instead of `test` you could use something like `common` or `template` so that people get that it is to be used as a starter. Otherwise LGTM

Thanks for your review on this @CynthiaKamau , although this PR was only meant to handle adding the metrics extension slot. I had made the mistake of testing out some changes on this same PR since it was still WIP, but they were not for review.

2024-03-10 11:42 UTC, raghavawasthi24 requested changes

2024-03-10 11:42 UTC, raghavawasthi24 commented on packages/esm-home-app/src/homepage-metrics/TestDataTile.component.tsx
> +          </div>
wrapping of `h2` by `div` has no significance.  You can put `h2` directly under `Title` element.

2024-03-20 12:10 UTC, pirupius commented on packages/esm-home-app/src/homepage-metrics/metrics-container.component.tsx
> +  const { data: visitSummaryData } = useVisitSummary();
These don't belong here. `esm-home` should just set up the slot and the logic should live in the respective esms similar to the way the appointments widget is lives in the appointments esm but is attached to the home dashboard slot

2025-02-22 15:46 UTC, closed without merging