(fix): add styling to accommodate metric tiles on the home page
openmrs/openmrs-esm-home pull request #214
Opened 2024-07-10 11:52 UTC by arodidev

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR introduces styling to the homepage metric tiles extension slot to accommodate metric tiles loaded as extensions from various esms.

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-07-11 01:17 UTC, brandones requested changes

2024-07-11 01:17 UTC, brandones commented on packages/esm-home-app/src/metrics/metrics.component.tsx
> +  return <ExtensionSlot name="home-metrics-tiles-slot" className={styles.container} />;
```suggestion
  return <ExtensionSlot name="home-metrics-tiles-slot" className={styles.metricTilesSlot} />;
```

2024-07-11 09:56 UTC, CynthiaKamau approved these changes

2024-07-15 17:35 UTC, brandones approved these changes

2024-07-15 17:36 UTC, merged