Remove the focus outline from the search link
openmrs/openmrs-esm-home pull request #63
Opened 2021-04-12 16:14 UTC by anjula-sack

https://issues.openmrs.org/browse/MF-535

2021-04-12 18:48 UTC, brandones commented on src/dashboard/home-dashboard.component.css
> +}
I suspect that this is actually the only code needed for this change. Why all the other stuff, what's that about?

2021-04-13 19:28 UTC, donaldkibet requested changes

2021-04-13 19:28 UTC, donaldkibet commented on src/dashboard/home-dashboard.component.css
> +  outline: none !important;
```suggestion
  outline: none;
```
We should avoid the use of `important` as it makes debugging in the future a challenge

2021-05-06 11:42 UTC, FlorianRappl commented
Is this PR still relevant?

@anjula-sack

2021-07-01 09:16 UTC, closed without merging